# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 540)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.backgroundLabel = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.backgroundLabel.setPalette(palette)
        self.backgroundLabel.setStyleSheet("font: 9pt \"Tahoma\";\n"
"font: 9pt \"Arial\";\n"
"font: 75 italic 84pt \"Arial\";\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.backgroundLabel.setScaledContents(False)
        self.backgroundLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.verticalLayout.addWidget(self.backgroundLabel)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inforLabel = QtWidgets.QLabel(self.centralwidget)
        self.inforLabel.setObjectName("inforLabel")
        self.horizontalLayout.addWidget(self.inforLabel)
        self.countLabel = QtWidgets.QLabel(self.centralwidget)
        self.countLabel.setObjectName("countLabel")
        self.horizontalLayout.addWidget(self.countLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuCookie = QtWidgets.QMenu(self.menubar)
        self.menuCookie.setObjectName("menuCookie")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menuCookie_2 = QtWidgets.QMenu(self.menubar)
        self.menuCookie_2.setObjectName("menuCookie_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openAction = QtWidgets.QAction(MainWindow)
        self.openAction.setObjectName("openAction")
        self.saveAction = QtWidgets.QAction(MainWindow)
        self.saveAction.setObjectName("saveAction")
        self.chromeAction = QtWidgets.QAction(MainWindow)
        self.chromeAction.setObjectName("chromeAction")
        self.firefoxAction = QtWidgets.QAction(MainWindow)
        self.firefoxAction.setObjectName("firefoxAction")
        self.helpAction = QtWidgets.QAction(MainWindow)
        self.helpAction.setObjectName("helpAction")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.analysisAction = QtWidgets.QAction(MainWindow)
        self.analysisAction.setObjectName("analysisAction")
        self.analysisAction_2 = QtWidgets.QAction(MainWindow)
        self.analysisAction_2.setObjectName("analysisAction_2")
        self.menu.addAction(self.openAction)
        self.menu.addAction(self.saveAction)
        self.menuCookie.addAction(self.chromeAction)
        self.menuCookie.addAction(self.firefoxAction)
        self.menu_2.addAction(self.helpAction)
        self.menu_2.addAction(self.aboutAction)
        self.menuCookie_2.addAction(self.analysisAction_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuCookie.menuAction())
        self.menubar.addAction(self.menuCookie_2.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backgroundLabel.setText(_translate("MainWindow", "cookie"))
        self.inforLabel.setText(_translate("MainWindow", "当前共有 "))
        self.countLabel.setText(_translate("MainWindow", "TextLabel"))
        self.comboBox.setItemText(0, _translate("MainWindow", "精确查找"))
        self.comboBox.setItemText(1, _translate("MainWindow", "模糊查找"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuCookie.setTitle(_translate("MainWindow", "Cookie操作"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.menuCookie_2.setTitle(_translate("MainWindow", "Cookie分析"))
        self.openAction.setText(_translate("MainWindow", "打开"))
        self.saveAction.setText(_translate("MainWindow", "另存为"))
        self.chromeAction.setText(_translate("MainWindow", "从Chrome提取"))
        self.firefoxAction.setText(_translate("MainWindow", "从Firefox提取"))
        self.helpAction.setText(_translate("MainWindow", "帮助"))
        self.aboutAction.setText(_translate("MainWindow", "关于我"))
        self.analysisAction.setText(_translate("MainWindow", "analysis"))
        self.analysisAction_2.setText(_translate("MainWindow", "分析当当网Cookie"))
import image
